meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: hazelcast-broker
    templates:
    - name: broker
      release: hazelcast
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( param "please set broker networks" ))


  - name: broker-registrar  
    lifecycle: errand
    instances: 1
    resource_pool: small_z1
    networks: (( param "set the errand network configs here" ))
    templates:
    - name: broker-registrar
      release: broker-registrar

  - name: broker-deregistrar
    lifecycle: errand
    instances: 1
    resource_pool: small_z1
    networks: (( param "set the errand network configs here" ))
    templates:
    - name: broker-deregistrar
      release: broker-registrar


networks: (( param "please set networks" ))

properties:  
  # other things are likely here too
  cf:
    admin_username: (( param "CF Admin Username" ))
    admin_password: (( param "CF Admin Password" ))
    api_url: (( param "CF API URL" ))
  broker:
    name: (( param "Broker name (registered with CF)" ))
    host: (( param "hostname/ip of broker node" ))
    port: 443 # or maybe 80?
    protocol: https # or maybe http?
    username: (( param "broker API username" ))
    password: (( param "broker API password" ))
